# Generated by Django 5.2 on 2025-04-28 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('Tree Plantation', 'Tree Plantation'), ('Solar Panel Installation', 'Solar Panel Installation'), ('Public Transport Usage', 'Public Transport Usage')], max_length=100)),
                ('proof_image', models.ImageField(upload_to='proofs/')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.userdata')),
            ],
        ),
    ]
