# Generated by Django 5.2 on 2025-04-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_submitproof_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitproof',
            name='description',
            field=models.TextField(blank=True, null='True'),
            preserve_default='True',
        ),
    ]
