# Generated by Django 5.2 on 2025-05-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_reward_userdata_earned_coins_userdata_spent_coins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitproof',
            name='image_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submitproof',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
