# Generated by Django 5.2 on 2025-05-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_submitproof_image_hash_submitproof_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitproof',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
