# Generated by Django 5.2 on 2025-05-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_submitproof_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitproof',
            name='coins_given',
            field=models.BooleanField(default=False),
        ),
    ]
