# Generated by Django 5.2 on 2025-05-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_submitproof_coins_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
