# Generated by Django 5.2 on 2025-05-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_userdata_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitproof',
            name='earned_coins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
