# Generated by Django 5.2 on 2025-05-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_submitproof_earned_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitproof',
            name='proof_image',
            field=models.FileField(upload_to='proofs/'),
        ),
    ]
