# Generated by Django 5.2 on 2025-05-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_reward_image_reward_stock_alter_reward_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='description',
            field=models.TextField(default='Default description here'),
        ),
    ]
