# Generated by Django 5.2 on 2025-05-09 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_remove_reward_description_remove_reward_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='cost',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='RedeemedReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_name', models.CharField(max_length=200)),
                ('cost', models.IntegerField()),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.userdata')),
            ],
        ),
        migrations.DeleteModel(
            name='Redemption',
        ),
    ]
