# Generated by Django 5.2 on 2025-05-11 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_submitproof_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitproof',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.userdata'),
        ),
    ]
