# Generated by Django 5.0.6 on 2025-08-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_alter_submitproof_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submitproof',
            name='activity_type',
            field=models.CharField(choices=[('Tree Plantation', 'Tree Plantation'), ('Solar Panel Installation', 'Solar Panel Installation'), ('Public Transport Usage', 'Public Transport Usage'), ('Use of Electric Vehicle', 'Use of Electric Vehicle')], max_length=100),
        ),
    ]
