# Generated by Django 5.0.6 on 2025-08-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_userdata_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitproof',
            name='claimed_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submitproof',
            name='claimed_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submitproof',
            name='exif_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submitproof',
            name='exif_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submitproof',
            name='live_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submitproof',
            name='live_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
