# Generated by Django 5.0.6 on 2025-08-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_submitproof_claimed_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submitproof',
            old_name='claimed_latitude',
            new_name='manual_latitude',
        ),
        migrations.RenameField(
            model_name='submitproof',
            old_name='claimed_longitude',
            new_name='manual_longitude',
        ),
        migrations.RemoveField(
            model_name='submitproof',
            name='exif_latitude',
        ),
        migrations.RemoveField(
            model_name='submitproof',
            name='exif_longitude',
        ),
        migrations.AddField(
            model_name='submitproof',
            name='suspicious',
            field=models.BooleanField(default=False),
        ),
    ]
