# Generated by Django 5.0.6 on 2025-10-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_rename_claimed_latitude_submitproof_manual_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submitproof',
            old_name='manual_latitude',
            new_name='claimed_latitude',
        ),
        migrations.RenameField(
            model_name='submitproof',
            old_name='manual_longitude',
            new_name='claimed_longitude',
        ),
        migrations.RemoveField(
            model_name='submitproof',
            name='suspicious',
        ),
        migrations.AddField(
            model_name='submitproof',
            name='exif_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submitproof',
            name='exif_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
