# Generated by Django 5.0.6 on 2025-10-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_rename_manual_latitude_submitproof_claimed_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitproof',
            name='calculated_distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
